#!/bin/bash
#
#-------------------------------------------------#
# Contributor: Tobias Holzmann                    #
# Updated on:  22 January 2018                    #
#-------------------------------------------------#
# Topic:       6DOF and AMI within a VAWT         #
# OpenFOAM:    5.x                                #
#-------------------------------------------------#
# Website:     https://Holzmann-cfd.de            #
# Email:       Tobias.Holzmann@Holzmann-cfd.de    #
#-------------------------------------------------#


#------------------------------------------------------------------------------
foamVersion="OpenFOAM-5.x"


#------------------------------------------------------------------------------
cd ${0%/*} || exit 1
clear
source clean
source .color
source .preamble


#------------------------------------------------------------------------------
if [ -f cad/backgroundMesh.unv ];
then
    echo "   - Background mesh exist, proceed..."
else
    echo "   - No background mesh exist, please build one"
    echo ""
    exit
fi


#------------------------------------------------------------------------------
echo -e "\n
Start meshing
-------------------------------------------------------------------------------
"


#------------------------------------------------------------------------------
echo -e "   - Create background mesh"
ideasUnvToFoam cad/backgroundMesh.unv > logMeshing


#------------------------------------------------------------------------------
echo -e "   - Extract feature edges for AMI"
surfaceFeatureExtract >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Meshing using snappyHexMesh (~ 1 minute)"
snappyHexMesh -overwrite >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Build 2D mesh"
extrudeMesh >> logMeshing
rm -rf 0


#------------------------------------------------------------------------------
echo -e "   - Modify boundaries for AMI"
createPatch -overwrite  >> logMeshing
rm -rf 0 constant/polyMesh/sets


#------------------------------------------------------------------------------
echo -e "   - Modify boundary type"
changeDictionary  >> logMeshing


#------------------------------------------------------------------------------
echo -e "\n
-------------------------------------------------------------------------------
End Meshing\n
"


#------------------------------------------------------------------------------
echo -e "   - Copy 0.org to 0"
cp -r 0.orig 0


#------------------------------------------------------------------------------
if [ `which pimpleDyMFoam` ]
then

    #--------------------------------------------------------------------------
    echo -e "   - Decompose the mesh"
    decomposePar > logSolve


    #--------------------------------------------------------------------------
    echo -e "   - Renumber the mesh again"
    mpirun -np 2 renumberMesh -overwrite -parallel >> logSolve


    #--------------------------------------------------------------------------
    echo -e "   - Start simulation (this will need some time)"
    mpirun -np 2 pimpleDyMFoam -parallel >> logSolve


    #--------------------------------------------------------------------------
else

    #--------------------------------------------------------------------------
    echo -en "   - Can not start simulation, '${RED}pimpleDyMFoam$NC'"
    echo -e " not available"


    #--------------------------------------------------------------------------
fi


#------------------------------------------------------------------------------
echo -e "   - End\n\n"


#------------------------------------------------------------------------------
